# Generated by Django 2.2.12 on 2020-04-13 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('iso_code', models.IntegerField()),
                ('ticker', models.TextField()),
                ('description', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Regions')),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('mobn', models.TextField(unique=True)),
                ('agent', models.TextField()),
                ('contract', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('type', models.TextField()),
                ('tag', models.TextField(blank=True, null=True)),
                ('trust_limit', models.BigIntegerField(null=True)),
                ('limit_per_transaction', models.BigIntegerField(null=True)),
                ('limit_per_day', models.BigIntegerField(null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Currencies')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Regions')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
